apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-stack-go-awq8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-stack-go-awq8
    app.kubernetes.io/part-of: testapppy
  name: devfile-stack-go-awq8
  namespace: johnmcollier-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-stack-go-awq8
status:
  loadBalancer: {}
