apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-stack-go-awq8
  namespace: johnmcollier-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:johnmcollier-tenant-devfile-stack-go-awq8
        name: my-go
        resources: {}
status: {}
