apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-ex-bu23
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-ex-bu23
    app.kubernetes.io/part-of: testapppy
  name: python-ex-bu23
  namespace: johnmcollier-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: python-ex-bu23
    weight: null
status: {}
